
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Uzair Afridi
 */
public class AddUser extends javax.swing.JFrame {

    /**
     * Creates new form AddUser
     */
    public AddUser() {
        initComponents();
        lblUserSteric.setVisible(false);
        lblPasswordSteric.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAddUserTitle = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtPasswordField = new javax.swing.JPasswordField();
        btnAddUser = new javax.swing.JButton();
        lblUserSteric = new javax.swing.JLabel();
        lblPasswordSteric = new javax.swing.JLabel();
        btnDeleteUser = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnShowAllUsers = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New User");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(240, 236, 227));

        lblAddUserTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblAddUserTitle.setForeground(new java.awt.Color(89, 110, 121));
        lblAddUserTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddUserTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-add-icon.png"))); // NOI18N
        lblAddUserTitle.setText("Add New User");

        lblUserName.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(57, 62, 70));
        lblUserName.setText("User Name:");

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(57, 62, 70));
        lblPassword.setText("Password:");

        txtUserName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtPasswordField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnAddUser.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnAddUser.setForeground(new java.awt.Color(57, 62, 70));
        btnAddUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-icon.png"))); // NOI18N
        btnAddUser.setText("Add");
        btnAddUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });

        lblUserSteric.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUserSteric.setForeground(new java.awt.Color(255, 0, 0));
        lblUserSteric.setText("*");

        lblPasswordSteric.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPasswordSteric.setForeground(new java.awt.Color(255, 0, 0));
        lblPasswordSteric.setText("*");

        btnDeleteUser.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDeleteUser.setForeground(new java.awt.Color(57, 62, 70));
        btnDeleteUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sign-delete-icon.png"))); // NOI18N
        btnDeleteUser.setText("Delete");
        btnDeleteUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(204, 255, 204));
        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(57, 62, 70));
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sign-error-icon.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnShowAllUsers.setBackground(new java.awt.Color(204, 255, 204));
        btnShowAllUsers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnShowAllUsers.setForeground(new java.awt.Color(57, 62, 70));
        btnShowAllUsers.setText("Show All Users");
        btnShowAllUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShowAllUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllUsersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAddUserTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUserName)
                            .addComponent(lblPassword))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnDeleteUser)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                            .addComponent(txtPasswordField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUserSteric)
                            .addComponent(lblPasswordSteric)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCancel)
                        .addGap(18, 18, 18)
                        .addComponent(btnShowAllUsers)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblAddUserTitle)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserSteric))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPasswordSteric)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPassword)
                        .addComponent(txtPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddUser)
                    .addComponent(btnDeleteUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnShowAllUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This Method Close the Add User Window
     */
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * This Method Add New User
     */
    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        lblUserSteric.setVisible(false);
        lblPasswordSteric.setVisible(false);

        if (txtUserName.getText().equals("")) {
            lblUserSteric.setVisible(true);
        }
        if (String.valueOf(txtPasswordField.getPassword()).equals("")) {
            lblPasswordSteric.setVisible(true);
        } else {
            Connection con = MyConnection.getConnection();
            PreparedStatement ps;
            try {
                ps = con.prepareStatement("INSERT INTO `user`(`username`, `password`) VALUES (?,?)");
                ps.setString(1, txtUserName.getText());
                ps.setString(2, String.valueOf(txtPasswordField.getPassword()));
                if (ps.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(null, "New User \"" + txtUserName.getText() + "\" has been Registered Successfully");
                    txtUserName.setText("");
                    txtPasswordField.setText("");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error !! " + ex.getMessage());
                txtUserName.setText("");
                txtPasswordField.setText("");
            }
        }
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
        Connection con = MyConnection.getConnection();
        PreparedStatement ps;
        try {
            ps = con.prepareStatement("DELETE FROM `user` WHERE username = ?");
            if (!"root".equals(txtUserName.getText())) {
                ps.setString(1, txtUserName.getText());
                if (ps.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(null, "User \"" + txtUserName.getText() + "\" Has been Deleted Successfully");
                    txtUserName.setText("");
                    txtPasswordField.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Admin cannot be Deleted");
                txtUserName.setText("");
                txtPasswordField.setText("");
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error !! " + ex.getMessage());
            txtUserName.setText("");
            txtPasswordField.setText("");
        }
    }//GEN-LAST:event_btnDeleteUserActionPerformed

    private void btnShowAllUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllUsersActionPerformed
        
        AllUser alluserObj = new AllUser();
        alluserObj.setVisible(true);
        alluserObj.pack();
        alluserObj.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btnShowAllUsersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnShowAllUsers;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAddUserTitle;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordSteric;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserSteric;
    private javax.swing.JPasswordField txtPasswordField;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
