
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Uzair Afridi
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        setIcon();
        lblUserSteric.setVisible(false);
        lblPassSteric.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblLoginForm = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPasswordField = new javax.swing.JPasswordField();
        btnAdminLogin = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblUserSteric = new javax.swing.JLabel();
        lblPassSteric = new javax.swing.JLabel();
        btnUserLogin = new javax.swing.JButton();

        jLabel1.setText("Login Form");

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login ");
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(240, 236, 227));

        lblLoginForm.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblLoginForm.setForeground(new java.awt.Color(57, 62, 70));
        lblLoginForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoginForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/man-icon.png"))); // NOI18N
        lblLoginForm.setText("Login To Your Diary");

        lblUserName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(57, 62, 70));
        lblUserName.setText("User Name:");

        txtUserName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        lblPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(57, 62, 70));
        lblPassword.setText("Password:");

        txtPasswordField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        btnAdminLogin.setBackground(new java.awt.Color(204, 255, 204));
        btnAdminLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdminLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sign-StandBy-icon_2.png"))); // NOI18N
        btnAdminLogin.setText("Admin Login");
        btnAdminLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminLoginActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(204, 255, 204));
        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sign-error-icon.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblUserSteric.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUserSteric.setForeground(new java.awt.Color(255, 0, 0));
        lblUserSteric.setText("*");

        lblPassSteric.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPassSteric.setForeground(new java.awt.Color(255, 0, 0));
        lblPassSteric.setText("*");

        btnUserLogin.setBackground(new java.awt.Color(204, 255, 204));
        btnUserLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUserLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sign-StandBy-icon_2.png"))); // NOI18N
        btnUserLogin.setText("User Login");
        btnUserLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUserLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLoginForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUserName)
                    .addComponent(lblPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnUserLogin)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdminLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPassSteric)
                    .addComponent(lblUserSteric))
                .addGap(74, 74, 74))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCancel)
                .addGap(93, 93, 93))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblLoginForm)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserSteric))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassSteric))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdminLogin)
                            .addComponent(btnUserLogin))
                        .addContainerGap(90, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    /**
     * This Method Redirect the User to Main Window If the User Name or Password
     * in correct
     */
    private void btnAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminLoginActionPerformed

        lblUserSteric.setVisible(false);
        lblPassSteric.setVisible(false);

        if (txtUserName.getText().equals("")) {
            lblUserSteric.setVisible(true);
        }
        if (String.valueOf(txtPasswordField.getPassword()).equals("")) {
            lblPassSteric.setVisible(true);
        } else {
            Connection con = MyConnection.getConnection();
            PreparedStatement ps;
            try {
                ps = con.prepareStatement("SELECT * FROM `user` WHERE username = ? AND password = ? ");
                ps.setString(1, "root");
                ps.setString(2, String.valueOf(txtPasswordField.getPassword()));
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    Main mf = new Main();
                    mf.setVisible(true);
                    mf.pack();
                    mf.setLocationRelativeTo(null);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(LoginForm.this, "Incorrect User Name or Password. \nTry Again");
                    txtUserName.setText("");
                    txtPasswordField.setText("");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(LoginForm.this, "Error !!" + ex.getMessage());
            } catch (NullPointerException e) {
                JOptionPane.showMessageDialog(LoginForm.this, "Communications Link Failure.\nStart Your Database.");
            }
        }

    }//GEN-LAST:event_btnAdminLoginActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnUserLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserLoginActionPerformed
        lblUserSteric.setVisible(false);
        lblPassSteric.setVisible(false);

        if (txtUserName.getText().equals("")) {
            lblUserSteric.setVisible(true);
        }
        if (String.valueOf(txtPasswordField.getPassword()).equals("")) {
            lblPassSteric.setVisible(true);
        } else {
            Connection con = MyConnection.getConnection();
            PreparedStatement ps;
            try {
                ps = con.prepareStatement("SELECT * FROM `user` WHERE username = ? AND password = ? ");
                // Checking that user is not root
                if (!"root".equals(txtUserName.getText())) {
                    ps.setString(1, txtUserName.getText());
                    ps.setString(2, String.valueOf(txtPasswordField.getPassword()));
                    ResultSet rs = ps.executeQuery();
                    if (rs.next()) {
                        Main mf = new Main();
                        mf.mnuAddUser.setVisible(false);
                        mf.setVisible(true);
                        mf.pack();
                        mf.setLocationRelativeTo(null);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(LoginForm.this, "Incorrect User Name or Password. \nTry Again");
                        resetFields();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "You Cannot be signed as Admin.");
                    resetFields();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(LoginForm.this, "Error !!" + ex.getMessage());
            } catch (NullPointerException e) {
                JOptionPane.showMessageDialog(LoginForm.this, "Communications Link Failure.\nStart Your Database Again.");
            }
        }
    }//GEN-LAST:event_btnUserLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("images/diary-book-icon.png")));
    }

    private void resetFields() {
        txtUserName.setText("");
        txtPasswordField.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminLogin;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnUserLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLoginForm;
    private javax.swing.JLabel lblPassSteric;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserSteric;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JPasswordField txtPasswordField;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
